# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Updated from v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: "(^mkdocs\\.yml$)"
    -   id: check-added-large-files
-   repo: https://github.com/rbubley/mirrors-prettier
    rev: 'v3.6.2'  # Updated to match package.json
    hooks:
    -   id: prettier
        types_or:
          - javascript
          - markdown
          - jsx
        additional_dependencies:
          - prettier@3.6.2                        # Updated to match package.json
          - 'prettier-plugin-organize-imports@4.3.0' # Updated to match package.json
