---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer & Social:
    - IT Tools:
        - abbr: IT
          href: https://tools.asbblog.com/
    - Github - avnit:
        - icon: si-github
          href: https://github.com/avnit/
    - Reddit:
        - icon: si-reddit
          href: https://reddit.com/

- Cloud Services:
    - Sophos Cloud:
        - icon: mdi-shield-check
          href: https://cloud.sophos.com
    - Cloudflare:
        - icon: si-cloudflare
          href: https://dash.cloudflare.com
    - Teleport:
        - icon: mdi-lan-connect
          href: https://clcreative.teleport.sh
    - Twingate:
        - icon: mdi-security-network
          href: https://clcreative.twingate.com
    - Netbird:
        - icon: mdi-bird
          href: https://app.netbird.io
    - Tailscale:
        - icon: si-tailscale
          href: https://login.tailscale.com

- Cloud Platforms:
    - AWS:
        - icon: si-amazonaws
          href: https://aws.amazon.com
    - Google Cloud:
        - icon: si-googlecloud
          href: https://console.cloud.google.com
    - Microsoft Azure:
        - icon: si-microsoftazure
          href: https://portal.azure.com
    - Digital Ocean:
        - icon: si-digitalocean
          href: https://cloud.digitalocean.com
    - CIVO:
        - icon: si-civo
          href: https://www.civo.com

- Entertainment:
    - Youtube:
        - icon: si-youtube
          href: https://youtube.com/
    - Netflix:
        - icon: si-netflix
          href: https://netflix.com/
    - Prime Video:
        - abbr: PV
          href: https://primevideo.com/
    - Disney+:
        - abbr: D+
          href: https://www.disneyplus.com/
    - Disney+ Hotstar:
        - abbr: DH
          href: https://www.disneyplus.com/
    - Hulu:
        - icon: si-hulu
          href: https://hulu.com/
    - HBO Max:
        - icon: si-hbo
          href: https://hbomax.com/
    - Apple TV+:
        - icon: si-appletv
          href: https://tv.apple.com/
    - Peacock:
        - abbr: PC
          href: https://peacocktv.com/
    - Paramount+:
        - abbr: P+
          href: https://paramountplus.com/
    - Discovery+:
        - abbr: D+
          href: https://discoveryplus.com/
    - Starz:
        - abbr: SZ
          href: https://starz.com/
    - Showtime:
        - abbr: ST
          href: https://showtime.com/
    - AMC+:
        - abbr: AC
          href: https://amcplus.com/
    - Epix:
        - abbr: EP
          href: https://epix.com/
    - Crunchyroll:
        - icon: si-crunchyroll
          href: https://crunchyroll.com/
    - Funimation:
        - abbr: FN
          href: https://funimation.com/
    - VRV:
        - abbr: VR
          href: https://vrv.co/
    - Shudder:
        - abbr: SH
          href: https://shudder.com/

- Repositories:
    - Homelab:
        - icon: si-github
          href: https://github.com/avnit/homepage
    - Boilerplates:
        - icon: si-github
          href: https://github.com/christianlempa/boilerplates
    - Cheat-Sheets:
        - icon: si-github
          href: https://github.com/christianlempa/cheat-sheets
    - Scripts:
        - icon: si-github
          href: https://github.com/christianlempa/scripts
    - Python4Eeryone:
        - icon: si-github
          href: https://github.com/avnit/Python-for-everyone
    - Bigbear-Video-Assets:
        - icon: si-github
          href: https://github.com/bigbeartechworld/big-bear-video-assets
