---
# https://gethomepage.dev/configs/settings
title: ASB Solutions Home Page
startUrl: https://asbblog.com
headerStyle: clean
hideErrors: true
bookmarksStyle: icons
fullWidth: true
language: en
locale: en
theme: dark
color: cyan
iconStyle: theme

# Performance optimizations
statusStyle: dot  # Lighter than "full" status style
disableCollapse: true  # Reduces re-renders
logLevel: debug


layout:
  Servers:
    Hypervisor:
      header: true
      style: column
    Storage-Server:
      header: true
      style: column
    DNS:
      header: true
      style: column
  Monitoring:
    header: true
    style: row
    columns: 4
  Automation:
    style: row
    columns: 4
  Business:
    header: true
    style: row
    columns: 4
  Media:
    style: row
    columns: 4
  Media2:
    style: row
    columns: 4
  Other:
    style: row
    columns: 2

quicklaunch:
  searchDescriptions: false  # Faster search
  hideInternetSearch: true
  hideVisitURL: true

hideVersion: true
showStats: false  # Disable stats to reduce API calls

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  finnhub: cvjjgu9r01qlscpcir7gcvjjgu9r01qlscpcir80
