---
# https://gethomepage.dev/configs/settings
title: ASB Solutions Home Page
startUrl: https://homepage2.asbblog.com
headerStyle: clean
hideErrors: true
bookmarksStyle: icons
fullWidth: true
language: en
locale: en
theme: dark
color: violet
iconStyle: theme

# Background configuration
background:
  image: https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2073&auto=format&fit=crop
  opacity: 30
  blur: sm
  saturate: 100
  brightness: 90


# Performance optimizations
statusStyle: dot  # Lighter than "full" status style
disableCollapse: true  # Reduces re-renders
logLevel: debug


layout:
  Monitoring:
    header: true
    style: row
    columns: 4
  Automation:
    style: row
    columns: 4
  Business:
    header: true
    style: row
    columns: 4
  Media:
    style: row
    columns: 4
  Media2:
    style: row
    columns: 4
  Other:
    style: row
    columns: 2
  Servers:
    Hypervisor:
      header: true
      style: column
    Storage-Server:
      header: true
      style: column
    DNS:
      header: true
      style: column

quicklaunch:
  searchDescriptions: false  # Faster search
  hideInternetSearch: true
  hideVisitURL: true

hideVersion: true
showStats: true  # Disable stats to reduce API calls

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  finnhub: cvjjgu9r01qlscpcir7gcvjjgu9r01qlscpcir80
