---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- weatherapi:
    units: metric
    apiKey: 37a1a38835174500ae5200432241202
    cache: 5

- datetime:
    text_size: xl
    format:
      timeStyle: short

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: google
    target: _blank

- openmeteo:
    label: Current
    latitude: 37.29
    longitude: -121.88
    cache: 5

- stocks:
    label: Stocks
    provider: finnhub
    watchlist:
      - AAPL
      - MSFT
      - AMZN
      - GOOGL
      - META
      - TSLA
      - NVDA
      - BRK.B
    showUSMarketStatus: true
